package rs.ac.bg.fon.CinemaServer.form;

import rs.ac.bg.fon.CinemaServer.threads.Server;

public class FrmMain extends javax.swing.JFrame {
    Server server;
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnDBSettings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnDBSettings.setText("DB Settings");
        btnDBSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDBSettings)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(28, 28, 28)
                        .addComponent(btnStop)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop))
                .addGap(39, 39, 39)
                .addComponent(btnDBSettings)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(Server.getEnd()){
          Server.setEnd(false);
          server = new Server();
          server.start(); 
          btnStart.setEnabled(false);
          btnStop.setEnabled(true);
        }
    }                                        

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if(!Server.getEnd()){    
            Server.setEnd(true);
            server.stopServer();
            btnStart.setEnabled(true);
            btnStop.setEnabled(false);
        }
    }                                       

    private void btnDBSettingsActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new FrmSettings(this, true).setVisible(true);
    }                                             



    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDBSettings;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    // End of variables declaration                   
}

